version: '3.1'
services:
  rmq:
    container_name: rmq
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"

#  postgresql:
#    image: postgres
#    container_name: postgresql
#    restart: always
#    environment:
#      POSTGRES_USER: svetlanamatveeva
#      POSTGRES_PASSWORD: 440924Sveta
#    ports:
#      - "5435:5432"
